In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install transformers

In [ ]:
from transformers import XLMRobertaTokenizer, TFXLMRobertaModel


In [ ]:
!pip install sentencepiece

In [ ]:
!pip install huggingface_hub


In [ ]:
!huggingface-cli login



    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|
    
    A token is already saved on your machine. Run `huggingface-cli whoami` to get more information or `huggingface-cli logout` if you want to log out.
    Setting a new token will erase the existing one.
    To login, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Token: 
Add token as git credential? (Y/n) Y
Token is valid (permission: read).
Cannot authenticate through git-cr

In [ ]:
!huggingface-cli login


    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|
    
    To login, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Token: 
Add token as git credential? (Y/n) Y
Token is valid (permission: read).
Cannot authenticate through git-credential as no helper is defined on your machine.
You might have to re-authenticate when pushing to the Hugging Face Hub.
Run the following command in your terminal in case you want to set the 'store' cre

paste the token below
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

In [ ]:
# Load model directly
from transformers import AutoTokenizer, TFAutoModel

tokenizer = AutoTokenizer.from_pretrained("Abhijnan/AxomiyaBERTa",use_auth_token=True)
bert_model = TFAutoModel.from_pretrained("Abhijnan/AxomiyaBERTa",use_auth_token=True,from_pt=True)

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1714: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
/usr/local/lib/python3.10/dist-packages/transformers/modeling_tf_utils.py:2634: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFAlbertModel: ['predictions.LayerNorm.weight', 'predictions.decoder.bias', 'albert.embeddings.position_ids', 'predictions.bias', 'predictions.dense.weight', 'predictions.decoder.weight', 'predictions.dense.bias', 'predictions.LayerNorm.bias']
- This IS expected if you are ini

In [ ]:
# Model Saving
save_model = False
model_weights_location = '/content/drive/MyDrive/hate rate/task 4/model saving/xlm-2lstm-2dense only/model_weights.pth'
model_architecture_location = "/content/drive/MyDrive/hate rate/task 4/model saving/xlm-2lstm-2dense only/model_architecture.pth"

# Model Training
num_epochs = 2


# Data Location
data_file_location = '/content/drive/MyDrive/hate rate/task 4/dataset/train_AH_preprocessed.csv'

# Fine-Tuning
fine_tune_bert = False

# Tokenization
max_token_length = 190

# LSTM Configuration
first_lstm_bidirectional = True

# Batch Size
batch_size = 8

# Trained Model Usage
use_saved_model = False
saved_model_weight_location = ''

# Binary Classification Threshold
classification_threshold = 0.5

# Save Final Model
save_final_model = False
final_model_weight_location = ''
final_model_architecture_location = ''

# Save Training/Validation Accuracy Dataframe
save_accuracy_dataframe = False
accuracy_dataframe_location = ''

# Test Data Usage
validation_data_percentage = 0.0
use_test_data = False

# Current BERT Model
model_name = "xlm-roberta-base"


max_tokenization_length=128

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv(data_file_location)

In [ ]:
#convert label to int
output=pd.Series()
for indx,row in df.iterrows():
  current=row['task_1']
  if(current=="NOT"):
    output.at[indx]=0
  else:
    output.at[indx]=1
df['output']=output


#finding longest sentence
maxx=0

for s in df['text']:
  s_len=len(s.split())
  if(s_len>maxx):
    sent=s
  maxx=max(s_len,maxx)


print(maxx)
# Pad sequences to a fixed length (adjust MAX_LEN if needed)
MAX_LEN = maxx

<ipython-input-11-5acdf9bf36d9>:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  output=pd.Series()


66


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split



# Splitting the dataframe into train and test sets
# _, datadf = train_test_split(df, test_size=0.2, random_state=42)

train_df=df
#train_df,data_df=train_test_split(df,test_size=validation_data_percentage,random_state=50)

# if(use_test_data):
#   val_df,test_df=train_test_split(data_df,test_size=0.5,random_state=100)
#   test_df=test_df.reset_index(drop=True)
# else:
#   val_df=data_df




#train_df,test_df=train_test_split(data_df,test_size=0.2,random_state=50)

# Reset the index of the DataFrame
train_df = train_df.reset_index(drop=True)
# Reset the index of the DataFrame
##val_df = val_df.reset_index(drop=True)



In [ ]:
# Make the model trainable (update weights during training)
for param in bert_model.layers:
    param.trainable = True


In [ ]:
df.columns

Index(['Unnamed: 0', 'S. No.', 'text', 'task_1', 'preprocessed_text',
       'output'],
      dtype='object')

In [ ]:

def get_embeddings(df):
  train_input_ids = []
  train_attention_masks = []
  train_labels = []
  for idx, row in df.iterrows():
    #text=row['preprocessed_text']
    text=row['text']
    if(text=='None'):
      text=''
    if(text=='nan'):
      text=''
    label=row['output']

    text_token=tokenizer(text,truncation=True,padding='max_length',max_length=180)
    train_input_ids.append(text_token['input_ids'])
    train_attention_masks.append(text_token['attention_mask'])
    train_labels.append(label)

  return train_input_ids,train_attention_masks,train_labels

    # text_input=[text_token['input_ids'],text_token['attention_mask']]


In [ ]:
train_input_ids,train_attention_masks,train_labels=get_embeddings(train_df)



In [ ]:
val_input_ids,val_attention_masks,val_labels=get_embeddings(val_df)

In [ ]:
# Convert to numpy arrays
import numpy as np
train_input_ids = np.array(train_input_ids)
train_attention_masks = np.array(train_attention_masks)
train_labels = np.array(train_labels)



In [ ]:

val_input_ids = np.array(val_input_ids)
val_attention_masks = np.array(val_attention_masks)
val_labels = np.array(val_labels)

In [ ]:
train_input_ids.shape
val_input_ids.shape


(404, 128)

In [ ]:
import tensorflow as tf

In [ ]:
#this one is working fine
train_dataset = tf.data.Dataset.from_tensor_slices(
    ({'input_ids': train_input_ids, 'attention_mask': train_attention_masks}, train_labels)
).batch(batch_size)


In [ ]:
val_dataset = tf.data.Dataset.from_tensor_slices(
    ({'input_ids': val_input_ids, 'attention_mask': val_attention_masks}, val_labels)
).batch(batch_size)


NameError: ignored

In [ ]:
type(inputs)

transformers.tokenization_utils_base.BatchEncoding

In [ ]:
# Example sentence with a masked word
sentence = "সঁচাই পৃথিৱীখন যে ইমান সুন্দৰ"

# Tokenize the sentence
inputs = tokenizer(sentence, return_tensors="tf")
type(inputs)
# Generate predictions for the masked token
outputs = bert_model(input_ids=inputs['input_ids'],attention_mask=inputs['attention_mask'])


In [ ]:
outputs

TFBaseModelOutputWithPooling(last_hidden_state=<tf.Tensor: shape=(1, 7, 768), dtype=float32, numpy=
array([[[ 0.09786534, -0.21150309, -2.425629  , ...,  0.01420348,
          1.42384   , -0.50649256],
        [ 0.39720172, -1.359025  ,  0.46150923, ...,  0.7663466 ,
         -1.1123885 , -1.4948075 ],
        [ 1.5523579 , -1.0888412 , -1.9005821 , ...,  0.7507171 ,
         -0.16748758, -2.0915804 ],
        ...,
        [ 2.1265585 ,  0.35555825, -0.9863867 , ..., -0.26307717,
          0.6379828 , -1.8828936 ],
        [ 1.8667408 ,  0.38056478, -1.3477347 , ..., -1.4901602 ,
          0.7580342 , -2.543373  ],
        [ 1.2044251 , -0.33213368, -0.00919001, ..., -0.2676668 ,
          1.164377  , -2.3437982 ]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-5.57867169e-01, -4.20049299e-03,  6.57549202e-01,
        -3.20209324e-01, -4.12219130e-02,  7.52124012e-01,
         5.81624091e-01,  1.30223036e-01,  3.05482954e-01,
         6.9212

In [ ]:
a=outputs.logits

In [ ]:
a.shape

torch.Size([1, 7, 32001])

In [ ]:
# Get the hidden states of the [CLS] token
cls_hidden_state = outputs.last_hidden_state[:, 0, :]

In [ ]:
import tensorflow as tf
from transformers import TFXLMRobertaModel

# Define model configuration
max_seq_length = 180


lstm1 = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(units=128, return_sequences=True, return_state=True))
# lstm2 = tf.keras.layers.LSTM(units=64, return_sequences=True, return_state=True)
#lstm3 = tf.keras.layers.LSTM(units=64, return_sequences=True, return_state=True)

dense_layers = tf.keras.Sequential([
    tf.keras.layers.Dense(units=256, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=128, activation='relu'),

    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=1)
])

sigmoid = tf.keras.layers.Activation('sigmoid')

# Define input layers
input_dict={
'input_ids':tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32, name='input_ids'),
'attention_mask':tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32, name='attention_mask')}

# # XLM-Roberta outputs
# xlm_output = xlm_roberta([input_ids, attention_mask])[0]
# XLM-Roberta outputs
xlm_output = bert_model(input_ids=input_dict['input_ids'], attention_mask=input_dict['attention_mask'])[0]

# LSTM 1
lstm_output, forward_hidden_state, forward_cell_state, backward_hidden_state, backward_cell_state= lstm1(xlm_output)

# # LSTM 2 (feeding output of LSTM 1)
_,lstm2_output, _ = lstm2(lstm_output)

# Dense layers
dense_output = dense_layers(lstm2_output)

output = sigmoid(dense_output)
output = tf.squeeze(output, axis=1)

#model = tf.keras.Model(inputs=[input_ids, attention_mask], outputs=output)
# Define the model
model = tf.keras.Model(inputs=input_dict, outputs=output)
# Move the model to GPU if available
# if tf.config.list_physical_devices('GPU'):
#     model = tf.keras.utils.multi_gpu_model(model, gpus=2)

# Compile the model


In [ ]:
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau

n_epochs=100
#optimizer = tf.keras.optimizers.legacy.AdamW(learning_rate=0.1, decay=0.001)
optimizer=tf.keras.optimizers.AdamW(
    learning_rate=0.001,
    weight_decay=0.004)

model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

# Create ReduceLROnPlateau callback
lr_scheduler = ReduceLROnPlateau(monitor='val_loss', mode='min', factor=0.7, patience=1, verbose=1)

# Train the model using fit method
history = model.fit(
    train_dataset,  # Replace with your training dataset
    epochs=n_epochs,
    callbacks=[lr_scheduler],
    batch_size=32,
    verbose=1,

    use_multiprocessing=True

)


Epoch 1/100


505/505 [==============================] - ETA: 0s - loss: 0.6860 - accuracy: 0.1089

505/505 [==============================] - 144s 204ms/step - loss: 0.6860 - accuracy: 0.1089 - lr: 0.0010
Epoch 2/100
505/505 [==============================] - ETA: 0s - loss: 0.6831 - accuracy: 0.1307

505/505 [==============================] - 94s 186ms/step - loss: 0.6831 - accuracy: 0.1307 - lr: 0.0010
Epoch 3/100
505/505 [==============================] - ETA: 0s - loss: 0.6813 - accuracy: 0.1069

505/505 [==============================] - 94s 185ms/step - loss: 0.6813 - accuracy: 0.1069 - lr: 0.0010
Epoch 4/100
505/505 [==============================] - ETA: 0s - loss: 0.6829 - accuracy: 0.1050

505/505 [==============================] - 94s 186ms/step - loss: 0.6829 - accuracy: 0.1050 - lr: 0.0010
Epoch 5/100
505/505 [==============================] - ETA: 0s - loss: 0.6817 - accuracy: 0.1149

505/505 [==============================] - 94s 186ms/step - loss: 0.6817 - accuracy: 0.1149 - lr: 0.0010
Epoch 6/100
505/505 [==============================] - ETA: 0s - loss: 0.6808 - accuracy: 0.1129

505/505 [==============================] - 94s 186ms/step - loss: 0.6808 - accuracy: 0.1129 - lr: 0.0010
Epoch 7/100
505/505 [==============================] - ETA: 0s - loss: 0.6803 - accuracy: 0.1248

505/505 [==============================] - 94s 186ms/step - loss: 0.6803 - accuracy: 0.1248 - lr: 0.0010
Epoch 8/100
505/505 [==============================] - ETA: 0s - loss: 0.6803 - accuracy: 0.1485

505/505 [==============================] - 94s 186ms/step - loss: 0.6803 - accuracy: 0.1485 - lr: 0.0010
Epoch 9/100
505/505 [==============================] - ETA: 0s - loss: 0.6808 - accuracy: 0.1426

505/505 [==============================] - 94s 185ms/step - loss: 0.6808 - accuracy: 0.1426 - lr: 0.0010
Epoch 10/100
505/505 [==============================] - ETA: 0s - loss: 0.6803 - accuracy: 0.1129

505/505 [==============================] - 94s 186ms/step - loss: 0.6803 - accuracy: 0.1129 - lr: 0.0010
Epoch 11/100
505/505 [==============================] - ETA: 0s - loss: 0.6802 - accuracy: 0.1109

505/505 [==============================] - 94s 185ms/step - loss: 0.6802 - accuracy: 0.1109 - lr: 0.0010
Epoch 12/100
434/505 [========================>.....] - ETA: 13s - loss: 0.6804 - accuracy: 0.1406

KeyboardInterrupt: ignored